Infoeduka/urls.py
from django.contrib import admin
from django.urls import path, include

from Infoeduka.settings import BASE_DIR

from django.http import HttpResponse
import os


def check_permissions(request):
    db_path = BASE_DIR / "tmp" / "db.sqlite3"
    db_path2 = "tmp/db.sqlite3"
    db_path3 = os.path.join("/tmp", "db.sqlite3")
    db_path4 = os.path.join("tmp", "db.sqlite3")
    tmp_dir_writable = os.access("tmp", os.W_OK)
    tmp_dir_writable2 = os.access("/tmp", os.W_OK)
    return HttpResponse(
        f'Database {db_path} writable: {os.access(db_path, os.W_OK)} <br> \
          Database {db_path2} writable: { os.access( db_path2, os.W_OK)} <br> \
          Database {db_path3} writable: {os.access(db_path3, os.W_OK)} <br> \
          Database {db_path4} writable: {os.access(db_path4, os.W_OK)} <br> \
          tmp directory writable: {tmp_dir_writable} <br> \
          /tmp directory writable: {tmp_dir_writable2} <br> \
          GAE_ENV: { os.getenv("GAE_ENV", "")}'
    )


urlpatterns = [
    path("", include("main.urls")),
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("check-permissions/", check_permissions),
]

main/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path("", RedirectView.as_view(url="obavijesti")),
    path("obavijesti", views.obavijesti, name="obavijesti"),
    path("obavijesti/unesi", views.obavijesti_nova, name="obavijesti_nova"),
    path("obavijesti/obrisi/<int:id>", views.obrisi_obavijest, name="obrisi_obavijest"),
    path("obavijesti/uredi/<int:id>", views.uredi_obavijest, name="uredi_obavijest"),
    path("kolegiji", views.kolegiji, name="kolegiji"),
    path("kolegij/unesi", views.kolegij_novi, name="kolegij_novi"),
    path("kolegij/obrisi/<int:id>", views.obrisi_kolegij, name="obrisi_kolegij"),
    path("kolegij/uredi/<int:id>", views.uredi_kolegij, name="uredi_kolegij"),
    path("predavaci", views.predavaci, name="predavaci"),
    path("predavaci/unesi", views.predavaci_novi, name="predavaci_novi"),
    path("predavaci/obrisi/<int:id>", views.obrisi_predavaca, name="obrisi_predavaca"),
    path("predavaci/uredi/<int:id>", views.uredi_predavaca, name="uredi_predavaca"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Kolegij(models.Model):
    predavaci = models.ManyToManyField(User,
                                       limit_choices_to={"is_staff": False})
    naziv = models.CharField(max_length=100)

    def __str__(self):
        return self.naziv

    class Meta:
        verbose_name_plural = "Kolegiji"


class Obavijest(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    kolegij = models.ForeignKey(Kolegij, on_delete=models.CASCADE)
    naziv = models.CharField(max_length=100)
    opis = models.TextField()
    datum_objave = models.DateTimeField(auto_now_add=True)
    datum_isteka = models.DateTimeField()

    def __str__(self):
        return self.naziv

    class Meta:
        verbose_name_plural = "Obavijesti"

main/forms.py
from django import forms
from main.models import Obavijest, Kolegij
from django.contrib.auth.models import User
from django.utils.timezone import now


class ObavijestForm(forms.ModelForm):
    class Meta:
        model = Obavijest
        fields = ["kolegij", "naziv", "opis", "datum_isteka"]
        widgets = {
            "datum_isteka": forms.DateInput(
                attrs={"type": "date", "min": now().strftime("%Y-%m-%d")},
            )
        }

    def __init__(self, user=None, *args, **kwargs):
        super(ObavijestForm, self).__init__(*args, **kwargs)

        if user and not user.is_staff:
            self.fields["kolegij"].queryset = self.fields["kolegij"].queryset.filter(
                predavaci__in=[user]
            )


class KolegijForm(forms.ModelForm):
    predavaci = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(is_staff=False)
    )

    class Meta:
        model = Kolegij
        fields = ["predavaci", "naziv"]


class PredavacForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password"]
        widgets = {
            "first_name": forms.TextInput(attrs={"required": "required"}),
            "last_name": forms.TextInput(attrs={"required": "required"}),
            "email": forms.EmailInput(attrs={"required": "required"}),
            "password": forms.PasswordInput(attrs={"required": "required"}),
        }

main/views.py
from datetime import datetime, time, timedelta
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Kolegij, Obavijest
from .forms import ObavijestForm, KolegijForm, PredavacForm


def obavijesti(request):
    obavijesti = Obavijest.objects.filter(
        datum_isteka__gte=datetime.combine(datetime.now(), time.min)
    ).order_by("-datum_objave")
    return render(request, "main/obavijesti.html", {"obavijesti": obavijesti})


def kolegiji(request):
    kolegiji = (
        Kolegij.objects.filter(predavaci=request.user)
        if not request.user.is_staff
        else Kolegij.objects.all()
    )
    return render(request, "main/kolegiji.html", {"kolegiji": kolegiji})


def predavaci(request):
    predavaci = User.objects.filter(is_staff=False)
    return render(request, "main/predavaci.html", {"predavaci": predavaci})


def obavijesti_nova(request):
    if request.method == "POST":
        form = ObavijestForm(data=request.POST)
        if form.is_valid():
            obavijest = form.save(commit=False)
            obavijest.autor = request.user
            obavijest.save()
            return redirect("/obavijesti")
    else:
        form = ObavijestForm(user=request.user)
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Nova obavijest",
            "button_action": "Unesi obavijest",
        },
    )


def predavaci_novi(request):
    if request.method == "POST":
        form = PredavacForm(request.POST)
        if form.is_valid():
            predavac = form.save(commit=False)
            predavac.username = form.cleaned_data["email"]
            predavac.set_password(form.cleaned_data["password"])
            predavac.save()
            return redirect("/predavaci")
    else:
        form = PredavacForm()
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Novi predavač",
            "button_action": "Unesi predavača",
        },
    )


def kolegij_novi(request):
    if request.method == "POST":
        form = KolegijForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/kolegiji")
    else:
        form = KolegijForm()
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Novi kolegij",
            "button_action": "Unesi kolegij",
        },
    )


def uredi_obavijest(request, id):
    data = Obavijest.objects.get(id=id)
    if request.method == "POST":
        form = ObavijestForm(data=request.POST)
        if form.is_valid():
            data.kolegij = form.cleaned_data["kolegij"]
            data.naziv = form.cleaned_data["naziv"]
            data.opis = form.cleaned_data["opis"]
            data.datum_isteka = form.cleaned_data["datum_isteka"]
            data.save()
            return redirect("/obavijesti")
    else:
        form = ObavijestForm(instance=data, user=request.user)
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Uredi obavijest",
            "button_action": "Spremi promjene",
        },
    )


def uredi_kolegij(request, id):
    data = Kolegij.objects.get(id=id)
    if request.method == "POST":
        form = KolegijForm(request.POST)
        if form.is_valid():
            data.predavaci.set(form.cleaned_data["predavaci"])
            data.naziv = form.cleaned_data["naziv"]
            data.save()
            return redirect("/kolegiji")
    else:
        form = KolegijForm(instance=data)
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Uredi kolegij",
            "button_action": "Spremi promjene",
        },
    )


def uredi_predavaca(request, id):
    data = User.objects.get(id=id)
    if request.method == "POST":
        form = PredavacForm(request.POST)
        if form.is_valid():
            data.first_name = form.cleaned_data["first_name"]
            data.last_name = form.cleaned_data["last_name"]
            data.username = form.cleaned_data["email"]
            data.email = form.cleaned_data["email"]
            data.set_password(form.cleaned_data["password"])
            data.save()
            return redirect("/predavaci")
    else:
        data.password = ""
        form = PredavacForm(instance=data)
    return render(
        request,
        "main/forma.html",
        {
            "form": form,
            "form_title": "Uredi predavača",
            "button_action": "Spremi promjene",
        },
    )


def obrisi_obavijest(request, id):
    Obavijest.objects.get(id=id).delete()
    return redirect("/obavijesti")


def obrisi_kolegij(request, id):
    Kolegij.objects.get(id=id).delete()
    return redirect("/kolegiji")


def obrisi_predavaca(request, id):
    User.objects.get(id=id).delete()
    return redirect("/predavaci")

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% load static %}
  <link rel="icon" href="{% static 'main/favicon.png' %}"
    type="image/png" />
  <style>
    body {
      font-family: sans-serif;
      margin: 0;
      --custombg: linear-gradient(339deg, #fd841f 0%, #e14d2a 40%, #cd104d 68%, #9c2c77 100%);
      background-color: rgb(240, 240, 240);
      min-height: 100vh;
    }
    form input, form select, form textarea {
      display: block;
      width: 100%;
      margin-top: 10px;
      border: none;
      box-sizing: border-box;
      padding: 5px 14px;
      outline: none;
      box-shadow: 1px 1px 10px -5px #7d0000;
      border-radius: 15px;
      resize: none;
      font-family: sans-serif;
    }
    nav {
      position: sticky;
      top: 0;
      z-index: 1;
      display: flex;
      justify-content: space-between;
      align-items: center;
      background-color: #151515;
      padding: 20px 30px;
      font-size: 18px;
      flex-direction: row;
    }
    @media screen and (max-width: 600px) {
      nav {
        flex-direction: column;
      }
      #navigation {
        width: 100%;
        flex-wrap: wrap;
        justify-content: space-between;
        order: 2;
      }
      #navigation > a:first-child {
        display: none;
      }
      #navigation a {
        margin: 0;
      }
      #name-signout {
        margin-bottom: 25px;
        font-size: 14px;
      }
    }
    nav a {
      text-decoration: none;
      color: white;
    }
    nav img {
      margin-right: 30px;
      width: 122px;
      height: 36px;
    }
    .logout {
      position: relative;
      margin-left: 40px !important;
    }
    .logout::before {
      content: "";
      position: absolute;
      left: -20px;
      top: -5px;
      bottom: -5px;
      width: 2px;
      background: var(--custombg);
      border-radius: 5px;
    }
    #navigation {
      font-family: sans-serif;
      display: flex;
      align-items: center;
    }
    #name-signout {
      font-family: sans-serif;
      color: white;
    }
    .button {
      margin-left: 20px;
      position: relative;
    }
    .button::after {
      content: "";
      position: absolute;
      top: calc(100% + 3px);
      right: 50%;
      left: -3px;
      height: 2px;
      background: var(--custombg);
      transition: 250ms right, 250ms opacity;
      opacity: 0;
      border-radius: 5px;
    }
    .button:hover::after, .button.active::after {
      right: -3px;
      opacity: 1;
    }
    #admin-color {
      color: #fd841f;
    }
    .cool-button {
      display: block;
      background: linear-gradient(339deg, #fd841f, #e14d2a,#cd104d, #9c2c77, #cd104d, #e14d2a, #fd841f);
      background-position: 0 0;
      background-size: 200% 200%;
      color: white;
      border: none;
      border-radius: 15px;
      margin: 10px auto 0;
      padding: 10px 20px;
      width: 85%;
      cursor: pointer;
      transition: background-position 250ms;
    }
    .cool-button:hover,
    .cool-button:focus {
      background-position: 100% 100%;
    }
    .list-button {
      width: fit-content;
      text-decoration: none;
      margin: 30px auto 10px;
    }
    .list-container {
      margin: 45px auto;
      width: 700px;
      max-width: 100%;
    }
    .list-item {
      position: relative;
      padding: 20px;
      margin: 20px 0;
      box-shadow: 5px 5px 20px -10px rgba(115, 115, 115, 1);
      background: #fff;
      border-radius: 15px;
      line-height: 22px;
      overflow: hidden;
    }
    .list-item p {
      margin: 0;
    }
    .item-title {
      position: relative;
      top: -20px;
      left: -20px;
      display: inline-block;
      font-weight: bold;
      color: white;
      background-color: #e14d2a;
      padding: 5px 20px;
      border-radius: 0 0 15px 0;
      box-shadow: 5px 5px 20px -10px rgba(115, 115, 115, 1);
    }
    .item-buttons-container {
      margin-top: 10px;
      display: flex;
      justify-content: right;
      gap: 15px;
    }
    a[href*="uredi"], a[href*="obrisi"] {
      font-size: 13px;
      background-color: #e14d2a;
      color: white;
      border-radius: 10px;
      padding: 5px 10px;
      text-decoration: none;
    }
    a[href*="obrisi"] {
      background-color: #cd104d
    }
    .empty-list {
      text-align: center;
      font-size: 20px;
      margin-top: 30px;
    }
  </style>
  <title>{% block title %}Infoeduka{% endblock %}</title>
</head>

<body>
  {% if user.is_authenticated %}
  <nav>
    <div id="navigation">
      <a href="/"><img src="{% static 'main/logo-algebra.svg' %}" alt="logo" /></a>
      <a href="/obavijesti" class="button {% if "/obavijesti" in request.path %}active{% endif %}">Obavijesti</a>
      <a href="/kolegiji" class="button {% if "/kolegiji" in request.path %}active{% endif %}">{{ user.is_staff|yesno:"Kolegiji,Moji kolegiji" }}</a>
      <a href="/predavaci" class="button {% if "/predavaci" in request.path %}active{% endif %}">Predavači</a>
    </div>
    <div id="name-signout">
      {% if user.is_authenticated %}
      <span>{{ user.first_name }} {{ user.last_name }}</span>
      {% if user.is_staff %}
      <span id="admin-color">(Administrator)</span>{% else %}<span>(Predavač)</span>
      {% endif %}
      <a class="button logout" href="/logout">Odjava</a>
      {% endif %}
    </div>
  </nav>
  {% endif %}
  {% block content %}{% endblock %}
</body>

</html>

main/templates/main/forma.html
{% extends 'main/base.html' %}
{% block content %}
<style>
  #form-container {
    margin-top: 45px;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-grow: 1;
  }
  form {
    background: #fff;
    min-width: 300px;
    border-radius: 15px;
    box-shadow: 15px 15px 42px -12px rgba(115, 115, 115, 1);
  }
  label[for="id_opis"] {
    display: block;
    margin-bottom: 10px
  }
  #form-title {
    text-align: center;
    color: white;
    font-size: 26px;
    padding: 20px 0;
    border-radius: 15px;
    background: linear-gradient(339deg, #fd841f, #e14d2a,#cd104d, #9c2c77, #cd104d, #e14d2a, #fd841f);
    background-position: 0 0;
    background-size: 200% 200%;
    animation: animate-title 1s forwards;
  }
  @keyframes animate-title {
    0% {
      background-position: 0 0;
    }
    100% {
      background-position: 100% 100%;
    }
  }
  #form-body {
    padding: 0 20px 20px 20px;
  }
</style>
  <div id="form-container">
    <form method="post">
      <div id="form-title">{{ form_title }}</div>
      <div id="form-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="cool-button">{{ button_action }}</button>
      </div>
    </form>
  </div>
{% endblock content %}

main/templates/main/kolegiji.html
{% extends 'main/base.html' %}
{% block content %}
<div class="list-container">
  {% if not kolegiji %}
  <div class="empty-list">Nema upisanih kolegija.</div>
  {% endif %}

  {% if user.is_staff %}
  <a href="kolegij/unesi" class="cool-button list-button">Unesi kolegij</a>
  {% endif %}

  {% for kolegij in kolegiji %}
  <div class="list-item">
    <div class="item-title">{{ kolegij }}</div><br>
    Predavači:
    {{ kolegij.predavaci.all|join:", " }}
    {% if user.is_staff %}
    <div class="item-buttons-container">
      <a
        href="kolegij/uredi/{{kolegij.id}}"
      >Uredi kolegij</a>
      <a
        href="kolegij/obrisi/{{kolegij.id}}"
        onClick="return confirm('Potvrdi brisanje kolegija?')"
      >Obriši kolegij</a>
    </div>
    {% endif %}
  </div>
  {% endfor %}

</div>
{% endblock content %}

main/templates/main/obavijesti-nova.html
{% extends 'main/base.html' %}
{% block content %}
  <h4>Nova obavijest</h4>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Unesi</button>
  </form>
{% endblock content %}

main/templates/main/obavijesti.html
{% extends 'main/base.html' %} {% block content %}
<div class="list-container">
  {% if not obavijesti %}
  <div class="empty-list">Nema upisanih obavijesti.</div>
  {% endif %}

  <a href="/obavijesti/unesi" class="cool-button list-button"
    >Unesi obavijest</a
  >

  {% for obavijest in obavijesti %}
  <div class="list-item">
    <div class="item-title">{{ obavijest.naziv }}</div>
    <br />
    {{ obavijest.opis|linebreaks }}
    <hr />
    Datum objave: {{ obavijest.datum_objave }}<br />
    Datum isteka: {{ obavijest.datum_isteka }}<br />
    Autor: {{ obavijest.autor }}<br />
    Kolegij: {{ obavijest.kolegij }}<br />
    {% if user.is_staff or obavijest.autor == user %}
    <div class="item-buttons-container">
      <a href="obavijesti/uredi/{{obavijest.id}}">Uredi obavijest</a>
      <a
        href="obavijesti/obrisi/{{obavijest.id}}"
        onClick="return confirm('Potvrdi brisanje obavijesti?')"
        >Obriši obavijest</a
      >
    </div>
    {% endif %}
  </div>
  {% endfor %}
</div>
{% endblock content %}

main/templates/main/predavaci.html
{% extends 'main/base.html' %}
{% block content %}
<div class="list-container">
  {% if not predavaci %}
  <div class="empty-list">Nema upisanih predavača.</div>
  {% endif %}

  {% if user.is_staff%}
  <a href="predavaci/unesi" class="cool-button list-button">Unesi predavača</a>
  {% endif %}

  {% for predavac in predavaci %}
  <div class="list-item">
    <div class="item-title"> {{ predavac.first_name }} {{ predavac.last_name }}</div><br>
    Email: {{ predavac.email }}
    {% if user.is_staff%}
    <div class="item-buttons-container">
      <a href="predavaci/uredi/{{predavac.id}}">Uredi predavača</a>
      <a
        href="predavaci/obrisi/{{predavac.id}}"
        onClick="return confirm('Potvrdi brisanje obavijesti?')"
        >Obriši predavača</a
      >
    </div>
    {% endif %}
  </div>
{% endfor %}

{% endblock content %}